"""initial

Revision ID: f7d1bbf56602
Revises: 
Create Date: 2026-04-11 11:05:19.983640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d1bbf56602'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orgs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=True),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graphs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parent_graph_id', sa.Uuid(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('definition_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.ForeignKeyConstraint(['parent_graph_id'], ['graphs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mcp_servers',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('transport', sa.String(length=16), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('command', sa.String(length=512), nullable=True),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('env_vars', sa.JSON(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('org_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['orgs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_edges',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('source_node_key', sa.String(length=128), nullable=False),
    sa.Column('target_node_key', sa.String(length=128), nullable=False),
    sa.Column('condition', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('graph_nodes',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('graph_id', sa.Uuid(), nullable=False),
    sa.Column('node_key', sa.String(length=128), nullable=False),
    sa.Column('node_type', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('ref_id', sa.Uuid(), nullable=True),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['graph_id'], ['graphs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('graph_nodes')
    op.drop_table('graph_edges')
    op.drop_table('mcp_servers')
    op.drop_table('graphs')
    op.drop_table('agents')
    op.drop_table('users')
    op.drop_table('orgs')
    # ### end Alembic commands ###
